---
abstract: 'Make your object constructor collect all unknown attributes'
author:
  - 'Mark Morgan <makk384@gmail.com>'
  - 'Karen Etheridge <ether@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-SlurpyConstructor
requires:
  Moose: 0.94
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX-SlurpyConstructor
  repository: https://github.com/karenetheridge/MooseX-Slurpyconstructor.git
version: 1.2
